#!/bin/bash
# for use on systems that have python, but no jq installed
# not nearly as functional as jq, but good for making json
# more readable
python -c 'import sys,json;print(json.dumps(json.load(sys.stdin),indent=4,sort_keys=True));'
